### ISSUE TITLE
web demo

### ISSUE THREAD

**Issue by abdelaziz-mahdy** [jinyus/rainbench#2]
I recently noticed the repository from my GitHub activity. I have an interest in benchmark applications, so I'm keen on trying it out. Could you provide a GitHub page as a demonstration for this application?

**Comment by zupat** [comment]
Hey, I wanted to make a web demo but it uses too much memory and stalls out

**Comment by abdelaziz-mahdy** [comment]
oh ok, thank you

**Comment by abdelaziz-mahdy** [comment]
if its okay can you put the results of the tests in readme?

**Comment by zupat** [comment]
@zezo357  added results along with video: https://github.com/jinyus/rainbench#results

**Comment by abdelaziz-mahdy** [comment]
> @zezo357 added results along with video: https://github.com/jinyus/rainbench#results

thank you very much
